server:
    port: 8080
    contextPath: /product-manager
spring: 
    datasource: 
        url: jdbc:mysql://localhost:3306/product_manager?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
jfish:
    security:
        logoutUrl: /logout
        syncPermissionData: true
siteConfig:
    uploadImageAccessPath: http://localhost/img/manager
    upload:
        #storeType: ftp
        #ftpServer: 127.0.0.1
        #ftpUser: test
        #ftpPassword: test
        fileStorePath: G:/temp/upload_files
        appContextDir: manager
        #maxUploadSize: 1024
